import os
from pathlib import Path

# Fix: Derive dynamically from script location instead of hardcoding
root_dir = Path(__file__).resolve().parent
docs_dir = root_dir / 'docs'
docs_dir.mkdir(parents=True, exist_ok=True)

datestamp = '070626'
version = 'v1.0'
doc_title = 'SustainAI_Codebase_Audit_Report'
doc_filename = f'{doc_title}_{version}_{datestamp}.md'
out_path = docs_dir / doc_filename

# Fix: Add .venv to IGNORE_DIRS
IGNORE_DIRS = {'.git', '__pycache__', '.pytest_cache', 'data', 'outputs', '.mypy_cache', 'tmp', '.venv', 'venv', 'env'}

def generate_tree(dir_path: Path, prefix: str = '') -> str:
    tree_str = ''
    try:
        entries = sorted([e for e in dir_path.iterdir() if e.name not in IGNORE_DIRS])
    except PermissionError:
        return ''
    
    for i, entry in enumerate(entries):
        if entry.is_file() and ("Codebase_Audit_Report" in entry.name or entry.suffix == ".pdf"):
            continue
        is_last = (i == len(entries) - 1)
        connector = '└── ' if is_last else '├── '
        tree_str += f'{prefix}{connector}{entry.name}\n'
        
        if entry.is_dir():
            extension = '    ' if is_last else '│   '
            tree_str += generate_tree(entry, prefix + extension)
            
    return tree_str

def get_code_files(dir_path: Path) -> list[Path]:
    files = []
    for entry in dir_path.iterdir():
        if entry.name in IGNORE_DIRS:
            continue
        if entry.is_dir():
            # Include .json files if they are in models/
            files.extend(get_code_files(entry))
        else:
            if "Codebase_Audit_Report" in entry.name or entry.suffix == ".pdf":
                continue
            rel = entry.relative_to(root_dir)
            # Include docs/*.md, models/*.json, and the standard code
            if 'docs' in rel.parts and entry.suffix == '.md':
                files.append(entry)
            elif 'models' in rel.parts and entry.suffix == '.json':
                files.append(entry)
            elif entry.name in ('Makefile', 'Dockerfile', '.gitignore', '.env.example', 'README.md') or entry.suffix in ('.py', '.toml', '.yaml', '.tf'):
                files.append(entry)
    return sorted(files)

tree_output = f'{root_dir.name}/\n' + generate_tree(root_dir)
files = get_code_files(root_dir)

# Fix: Remove fabricated claims. Keep strictly factual.
content = f"""# {doc_title.replace('_', ' ')} - {version}
**Date**: July 6, 2026
**Generated by**: Autonomy Build Agent

## 1. Components Built List
The following components have been constructed according to the Technical Requirements Document (TRD) outline:
1. Repository Scaffolding (configs, terraform, pyproject.toml)
2. Schema & Config Engine implementation (Pydantic typing)
3. Data Downloader/Acquisition scripts
4. Data Ingestion (schema validation, monotonically-increasing verification, capping)
5. Feature Engineering (dynamic sensor drops, rolling statistics)
6. Model Training & Selection (Keras MLP versus local baseline)
7. Exception Generation (Dynamic mapping thresholds)
8. Triage Agent Layer (Read-only tools, LLM interface stubs, safe-guardrails)
9. FastAPI Async Service Layer (Event-driven endpoints)
10. End-to-end Evaluation Harness

## 2. Complete Directory Tree Structure
```text
{tree_output}
```

## 3. Source Code Ledger
The source code and artifacts generated are contained below.

"""

for f in files:
    try:
        ext = f.suffix.replace('.', '')
        if f.name == 'Makefile': ext = 'make'
        elif f.name == 'Dockerfile': ext = 'dockerfile'
        elif ext == 'tf': ext = 'hcl'
        elif ext == 'json': ext = 'json'
        
        file_content = f.read_text(encoding='utf-8')
        rel_path = f.relative_to(root_dir).as_posix()
        
        content += f"### `{rel_path}`\n"
        content += f"```{ext}\n{file_content}\n```\n\n"
    except Exception as e:
        content += f"### `{f.relative_to(root_dir).as_posix()}`\n*Error reading file: {e}*\n\n"

out_path.write_text(content, encoding='utf-8')
print(f'Successfully wrote audit report to {out_path}')
