import sys
import os
import pytest
import subprocess
import json
import shutil
from pathlib import Path

def test_t12_pipeline_determinism(tmp_path):
    """T-12: Verify pipeline determinism in stub mode.
    
    Runs evaluate twice back to back and asserts identical output maps.
    This assumes `make setup` and model training has already been run on static seeds.
    """
    repo_root = Path(__file__).parent.parent.absolute()
    
    # Evaluate run A
    proc1 = subprocess.run(
        [sys.executable, "-m", "sustainai.harness.evaluate"],
        capture_output=True,
        text=True,
        cwd=repo_root,
        env=os.environ
    )
    assert proc1.returncode == 0, f"Run A failed. STDERR: {proc1.stderr}"
    
    # The script prints "EVAL ID: <id>" at the end
    eval_id1 = next((line.split()[-1] for line in proc1.stdout.split('\n') if "EVAL ID:" in line), None)
    
    # Evaluate run B
    proc2 = subprocess.run(
        [sys.executable, "-m", "sustainai.harness.evaluate"],
        capture_output=True,
        text=True,
        cwd=repo_root,
        env=os.environ
    )
    assert proc2.returncode == 0, f"Run B failed. STDERR: {proc2.stderr}"
    eval_id2 = next((line.split()[-1] for line in proc2.stdout.split('\n') if "EVAL ID:" in line), None)
    
    assert eval_id1 is not None and eval_id2 is not None, "Evaluation runs failed to output ID."
    
    eval_dir1 = Path("outputs/eval") / eval_id1
    eval_dir2 = Path("outputs/eval") / eval_id2
    
    # Assert metrics identical (ignoring run_id, eval_id, wall_clock, latency in agent)
    with open(eval_dir1 / "metrics.json") as f:
        metrics1 = json.load(f)
    with open(eval_dir2 / "metrics.json") as f:
        metrics2 = json.load(f)
        
    for k in ("prediction_metrics", "total_test_engines"):
        assert metrics1[k] == metrics2[k]
        
    assert metrics1["agent_integrity"]["failure_rate"] == metrics2["agent_integrity"]["failure_rate"]
    assert metrics1["agent_integrity"]["total_processed"] == metrics2["agent_integrity"]["total_processed"]
        
    # Assert itemized identical
    with open(eval_dir1 / "per_engine.json") as f:
        pe1 = json.load(f)
    with open(eval_dir2 / "per_engine.json") as f:
        pe2 = json.load(f)
        
    assert pe1 == pe2
    
    # Teardown the temporal evaluation environments generated by test
    shutil.rmtree(eval_dir1)
    shutil.rmtree(eval_dir2)
